"""Unit tests for the pure-Python helpers inside ``compile.py``.

These tests lock in the early behaviours (carving, single-file
resolver, linker-script parsing) so later real-decomp churn can't
silently regress them.

Out of scope (deliberately):
  * Mocking the assembler / linker / ee-cc-wrap.  End-to-end build
    remains integration-tested via ``scripts/session_check.sh``.
  * Refactoring ``compile.py``.  If a helper is hard to test, the
    test contorts; this is documented coupling and a future task's
    problem.

Test inventory (one ``-k`` slice per helper):

    parse_carved_entries  — empty / with-tu / without-tu / malformed
    index_functions       — glabel/endlabel/nonmatching/alabel-skip/no-endlabel
    preamble_end_index    — finds `.section .text`, raises if missing
    split_monolithic      — middle-carve / pad-nop-swallow / not-present /
                            multi-carve order / overlap
    resolve_single_file_targets — 5 happy paths + 3 error shapes
    ld_script_objects     — order-preserving + dedup + carve-aware
"""
from __future__ import annotations

import json
import textwrap
from pathlib import Path

import pytest

import compile as cm


# --------------------------------------------------------------------------- #
# Tiny test helpers
# --------------------------------------------------------------------------- #
def _mkcfg(**overrides) -> cm.Config:
    """Build a minimal ``Config`` for tests that only need a subset of
    fields.  Anything not in ``overrides`` is filled with empty defaults.
    """
    raw = {
        "tools": {},
        "include_dirs": [],
        "defines": [],
        "c_flags": [],
        "as_flags": [],
        "dvp_as_flags": [],
        "linker_scripts": [],
        "linker_flags": [],
        "asm_sources_glob": [],
        "c_sources_glob": [],
        "vsm_sources_glob": [],
        "sdata_overrides": {},
        "build_dir": "build",
        "output_elf": "build/out.elf",
        "output_map": "build/out.map",
        "preserve_in_build": [],
        "objdiff": {},
        "section_flag_overrides": {},
        "carved_funcs": [],
    }
    raw.update(overrides)
    return cm.Config(raw=raw)


# Canonical 3-function synthetic monolithic.  Mirrors the real shape of
# asm/cod/000000.s: ee-as include, .set directives, .section .text,
# /* ... */ comment + nonmatching marker + glabel/endlabel triplets,
# inter-function pad nop.  Verified shape against the live file.
MONOLITHIC_3FN = textwrap.dedent(
    """\
    .include "macro.inc"

    .set noat
    .set noreorder

    .section .text, "ax"

    /* Generated by spimdisasm 1.40.3 */

    .align 3
    nonmatching alpha, 0x4

    glabel alpha
        /* 0 00100000 00000000 */  nop
    endlabel alpha
        /* 4 00100004 00000000 */  nop

    .align 3
    nonmatching beta, 0x8

    glabel beta
        /* 8 00100008 00000000 */  addiu $sp, $sp, -8
        /* C 0010000C 03E00008 */  jr    $ra
    endlabel beta
        /* 10 00100010 00000000 */  nop

    .align 3
    nonmatching gamma, 0x4

    glabel gamma
        /* 14 00100014 03E00008 */  jr    $ra
    endlabel gamma
    """
)


# --------------------------------------------------------------------------- #
# _parse_carved_entries
# --------------------------------------------------------------------------- #
class TestParseCarvedEntries:

    def test_empty_list_returns_empty(self):
        assert cm._parse_carved_entries(_mkcfg()) == []

    def test_entry_with_tu(self):
        cfg = _mkcfg(carved_funcs=[
            {"name": "func_00100000", "unit": "asm/cod/000000",
             "vaddr": "0x00100000", "size": 4,
             "tu": "src/cod/000000.c"}
        ])
        [entry] = cm._parse_carved_entries(cfg)
        assert entry.name == "func_00100000"
        assert entry.unit == "asm/cod/000000"
        assert entry.vaddr == 0x00100000
        assert entry.size == 4
        assert entry.tu == "src/cod/000000.c"

    def test_entry_without_tu(self):
        cfg = _mkcfg(carved_funcs=[
            {"name": "func_00100000", "unit": "asm/cod/000000",
             "vaddr": "0x00100000", "size": 4}
        ])
        [entry] = cm._parse_carved_entries(cfg)
        assert entry.tu is None

    def test_vaddr_accepts_int(self):
        cfg = _mkcfg(carved_funcs=[
            {"name": "f", "unit": "asm/cod/000000",
             "vaddr": 0x100000, "size": 4}
        ])
        [entry] = cm._parse_carved_entries(cfg)
        assert entry.vaddr == 0x100000

    def test_vaddr_accepts_decimal_string(self):
        cfg = _mkcfg(carved_funcs=[
            {"name": "f", "unit": "asm/cod/000000",
             "vaddr": "1048576", "size": 4}
        ])
        [entry] = cm._parse_carved_entries(cfg)
        assert entry.vaddr == 0x100000

    def test_doc_entries_filtered_via_underscore_name(self):
        # Documentation entries (name starts with `_`) are dropped by
        # Config.carved_funcs *before* _parse_carved_entries sees them.
        cfg = _mkcfg(carved_funcs=[
            {"name": "_doc", "unit": "asm/cod/000000",
             "vaddr": 0, "size": 0},
            {"name": "real", "unit": "asm/cod/000000",
             "vaddr": 0x100000, "size": 4},
        ])
        entries = cm._parse_carved_entries(cfg)
        assert [e.name for e in entries] == ["real"]

    def test_non_dict_entries_filtered(self):
        cfg = _mkcfg(carved_funcs=[
            "not a dict",
            {"name": "real", "unit": "asm/cod/000000",
             "vaddr": 0x100000, "size": 4},
        ])
        assert [e.name for e in cm._parse_carved_entries(cfg)] == ["real"]

    def test_malformed_missing_name_raises(self):
        cfg = _mkcfg(carved_funcs=[
            {"unit": "asm/cod/000000", "vaddr": 0, "size": 4}
        ])
        # No `name` key -> filtered out by Config.carved_funcs (empty
        # string), so the parsed list is just empty.
        assert cm._parse_carved_entries(cfg) == []

    def test_malformed_missing_unit_raises_keyerror(self):
        cfg = _mkcfg(carved_funcs=[
            {"name": "f", "vaddr": 0, "size": 4}
        ])
        with pytest.raises(KeyError):
            cm._parse_carved_entries(cfg)


# --------------------------------------------------------------------------- #
# _index_functions
# --------------------------------------------------------------------------- #
class TestIndexFunctions:

    def test_recognises_glabel_endlabel_pairs(self):
        lines = MONOLITHIC_3FN.splitlines(keepends=True)
        idx = cm._index_functions(lines)
        assert set(idx.keys()) == {"alpha", "beta", "gamma"}

    def test_block_start_points_at_align3(self):
        lines = MONOLITHIC_3FN.splitlines(keepends=True)
        idx = cm._index_functions(lines)
        start, glabel, _end = idx["alpha"]
        assert lines[start].strip() == ".align 3"
        assert lines[glabel].strip() == "glabel alpha"

    def test_block_end_swallows_trailing_pad_nop(self):
        """The carve unit extends through inter-function padding to the
        next function's `.align 3` line - 1, so the trailing `nop` after
        `endlabel alpha` is part of alpha's carve, not beta's fragment.
        """
        lines = MONOLITHIC_3FN.splitlines(keepends=True)
        idx = cm._index_functions(lines)
        _start, _glabel, end = idx["alpha"]
        # The carve unit for alpha should include the post-endlabel nop;
        # the next function's `.align 3` lives at end+1.
        assert "nop" in lines[end] or lines[end].strip() == ""
        assert lines[end + 1].strip() == ".align 3"

    def test_block_end_for_last_function_is_eof(self):
        lines = MONOLITHIC_3FN.splitlines(keepends=True)
        idx = cm._index_functions(lines)
        _start, _glabel, end = idx["gamma"]
        # gamma is the last function: its block_end_inclusive is the
        # last index in the source.
        assert end == len(lines) - 1

    def test_nonmatching_marker_inside_carve_unit(self):
        lines = MONOLITHIC_3FN.splitlines(keepends=True)
        idx = cm._index_functions(lines)
        start, _glabel, end = idx["alpha"]
        carve_unit = "".join(lines[start:end + 1])
        assert "nonmatching alpha, 0x4" in carve_unit

    def test_alabel_jlabel_ehlabel_skipped_in_upward_walk(self):
        """alabel/jlabel/ehlabel between `.align 3` and `glabel` must not
        break the upward walk to .align 3.  Real-world example: function
        with leading switch-table alabel sitting between the .align 3 and
        the glabel.
        """
        src = textwrap.dedent("""\
            .section .text, "ax"

            .align 3
            alabel some_aux_sym
            jlabel another_aux
            ehlabel eh_aux
            nonmatching real, 0x4

            glabel real
                nop
            endlabel real
            """)
        lines = src.splitlines(keepends=True)
        idx = cm._index_functions(lines)
        start, _glabel, _end = idx["real"]
        assert lines[start].strip() == ".align 3"

    def test_missing_endlabel_raises(self):
        src = textwrap.dedent("""\
            .section .text, "ax"

            .align 3
            glabel orphan
                nop
            """)
        lines = src.splitlines(keepends=True)
        with pytest.raises(cm.BuildError, match="no endlabel for 'orphan'"):
            cm._index_functions(lines)

    def test_alabel_not_eligible_as_carve_root(self):
        """alabel/jlabel/ehlabel define symbols, but `_index_functions`
        keys off `glabel` matches only — so an `alabel` name will not
        appear in the index and `_split_monolithic` rejects it with
        "function not present in monolithic".
        """
        src = textwrap.dedent("""\
            .section .text, "ax"

            .align 3
            alabel auxiliary_only
            """)
        lines = src.splitlines(keepends=True)
        idx = cm._index_functions(lines)
        assert idx == {}

    def test_no_endlabel_then_orphan_glabel_raises(self):
        """An unterminated function followed by another glabel still
        fails on the missing endlabel of the *first* function.
        """
        src = textwrap.dedent("""\
            .section .text, "ax"

            .align 3
            glabel first
                nop
            .align 3
            glabel second
                nop
            endlabel second
            """)
        lines = src.splitlines(keepends=True)
        with pytest.raises(cm.BuildError, match="no endlabel for 'first'"):
            cm._index_functions(lines)


# --------------------------------------------------------------------------- #
# _preamble_end_index
# --------------------------------------------------------------------------- #
class TestPreambleEndIndex:

    def test_finds_section_text(self):
        lines = MONOLITHIC_3FN.splitlines(keepends=True)
        end = cm._preamble_end_index(lines)
        assert lines[end - 1].lstrip().startswith(".section .text")
        # Returns the index one past the .section .text line.
        assert end >= 1

    def test_no_section_text_raises(self):
        lines = [".set noat\n", ".set noreorder\n"]
        with pytest.raises(cm.BuildError, match="no `.section .text`"):
            cm._preamble_end_index(lines)


# --------------------------------------------------------------------------- #
# _split_monolithic
# --------------------------------------------------------------------------- #
class TestSplitMonolithic:

    def test_carve_middle_function_emits_two_fragments(self):
        fragments, carved, ranges = cm._split_monolithic(MONOLITHIC_3FN, ["beta"])
        assert len(fragments) == 2
        assert set(carved.keys()) == {"beta"}
        assert len(ranges) == 1
        assert ranges[0][0] == "beta"

    def test_carved_text_contains_glabel_endlabel_and_nonmatching(self):
        _frags, carved, _ranges = cm._split_monolithic(MONOLITHIC_3FN, ["beta"])
        body = carved["beta"]
        assert "glabel beta" in body
        assert "endlabel beta" in body
        assert "nonmatching beta, 0x8" in body
        assert ".align 3" in body

    def test_carved_preamble_uses_labels_inc_not_macro_inc(self):
        """Carve preamble swaps `.include "macro.inc"` for `labels.inc`
        because ee-as (the SCE assembler) rejects macro.inc's modern-gas
        quoted-escape syntax.  Fragments keep macro.inc (mipsel-as path).
        """
        _frags, carved, _ranges = cm._split_monolithic(MONOLITHIC_3FN, ["beta"])
        body = carved["beta"]
        assert '.include "labels.inc"' in body
        assert '.include "macro.inc"' not in body

    def test_fragments_keep_macro_inc(self):
        fragments, _carved, _ranges = cm._split_monolithic(MONOLITHIC_3FN, ["beta"])
        # Both fragments must carry the macro.inc include — fragment 0
        # naturally (it owns the original preamble), fragment 1 because
        # we re-prepend the preamble for standalone assembly.
        for f in fragments:
            assert '.include "macro.inc"' in f
            assert '.include "labels.inc"' not in f

    def test_carved_function_bytes_not_in_remaining_fragments(self):
        """The carved function's body must not leak into either fragment
        — that would link-duplicate the bytes and break retail equality.
        """
        fragments, _carved, _ranges = cm._split_monolithic(MONOLITHIC_3FN, ["beta"])
        for f in fragments:
            assert "glabel beta" not in f
            assert "endlabel beta" not in f

    def test_pad_nop_swallowed_into_previous_carve(self):
        """The trailing `nop` between endlabel beta and the next `.align 3`
        must travel with beta, not with fragment-1 — otherwise fragment-1's
        `.align 3` finds the cursor misaligned and emits stray bytes.
        """
        fragments, carved, _ranges = cm._split_monolithic(MONOLITHIC_3FN, ["beta"])
        body = carved["beta"]
        # The hex comment "10 00100010" marks the trailing-pad nop.
        assert "00100010" in body
        # The second fragment must start cleanly at the gamma `.align 3`,
        # not at the trailing nop.
        # gamma's `.align 3` must be the first non-preamble directive.
        frag1 = fragments[1]
        post_preamble = frag1.split(".section .text", 1)[1]
        # The first non-empty / non-comment instruction should not be a nop.
        assert "00100010" not in post_preamble

    def test_first_fragment_inherits_preamble_naturally(self):
        """When carving from non-first position, fragment 0 contains the
        original preamble exactly — no re-prepend.  Fragment 0's length
        equals the slice from start to first carve's block_start.
        """
        fragments, _carved, ranges = cm._split_monolithic(MONOLITHIC_3FN, ["beta"])
        # Fragment 0 must start with the original `.include "macro.inc"`.
        assert fragments[0].startswith('.include "macro.inc"')
        # And it must contain alpha but not beta or gamma.
        assert "glabel alpha" in fragments[0]
        assert "glabel beta" not in fragments[0]
        assert "glabel gamma" not in fragments[0]
        # Tail fragment contains gamma.
        assert "glabel gamma" in fragments[1]

    def test_multi_carve_order_independent(self):
        """Passing names out of source order still emits fragments in
        source order — the function re-sorts by carve start line.
        """
        fragments, carved, ranges = cm._split_monolithic(
            MONOLITHIC_3FN, ["gamma", "alpha"]
        )
        assert len(fragments) == 3
        assert [r[0] for r in ranges] == ["alpha", "gamma"]
        # Middle fragment carries beta in full.
        assert "glabel beta" in fragments[1]
        assert "glabel alpha" not in fragments[1]
        assert "glabel gamma" not in fragments[1]

    def test_function_not_in_monolithic_raises(self):
        with pytest.raises(cm.BuildError, match="not present in monolithic"):
            cm._split_monolithic(MONOLITHIC_3FN, ["does_not_exist"])

    def test_carve_first_function(self):
        """Carving the very first function exercises the cursor == 0
        branch (fragment 0 is empty/just preamble, no re-prepend).
        """
        fragments, carved, _ranges = cm._split_monolithic(MONOLITHIC_3FN, ["alpha"])
        assert len(fragments) == 2
        assert "glabel alpha" not in fragments[0]
        assert "glabel alpha" not in fragments[1]
        assert "glabel alpha" in carved["alpha"]

    def test_carve_last_function(self):
        """Carving the last function: trailing fragment is preamble-only
        (or near-empty) and must still be well-formed.
        """
        fragments, carved, _ranges = cm._split_monolithic(MONOLITHIC_3FN, ["gamma"])
        assert len(fragments) == 2
        # Final fragment is preamble + tail (likely no glabels).
        assert "glabel gamma" not in fragments[-1]
        assert "glabel gamma" in carved["gamma"]
        # Fragment 0 retains alpha and beta.
        assert "glabel alpha" in fragments[0]
        assert "glabel beta" in fragments[0]


# --------------------------------------------------------------------------- #
# _carve_unit_size_bytes
#
# The LCF location counter needs the carve unit's TRUE byte span (body +
# trailing nop pad), not just the function body size.  Without the
# trailing-pad bytes, a TU-integrated C body smaller than the carve
# unit shifts every subsequent function in .text earlier, drifting the
# ELF sha256.
# --------------------------------------------------------------------------- #


class TestCarveUnitSizeBytes:
    """Coverage for ``_carve_unit_size_bytes``.

    The function counts instruction lines in a carved-fragment .s text
    (the form spimdisasm emits with ``/* FILE_OFF VRAM HEX_BYTES */``
    comment prefixes) and multiplies by 4 for MIPS.
    """

    def test_alpha_body_with_one_nop_pad(self):
        """``alpha`` = 1-insn 4-B body + 1 trailing nop = 8 B carve unit."""
        _frags, carved, _ranges = cm._split_monolithic(
            MONOLITHIC_3FN, ["alpha"]
        )
        assert cm._carve_unit_size_bytes(carved["alpha"]) == 8

    def test_beta_body_with_one_nop_pad(self):
        """``beta`` = 2-insn 8-B body + 1 trailing nop = 12 B carve unit."""
        _frags, carved, _ranges = cm._split_monolithic(
            MONOLITHIC_3FN, ["beta"]
        )
        assert cm._carve_unit_size_bytes(carved["beta"]) == 12

    def test_gamma_body_no_trailing_pad(self):
        """``gamma`` = 1-insn 4-B body, no trailing pad = 4 B carve unit."""
        _frags, carved, _ranges = cm._split_monolithic(
            MONOLITHIC_3FN, ["gamma"]
        )
        assert cm._carve_unit_size_bytes(carved["gamma"]) == 4

    def test_empty_string_returns_zero(self):
        assert cm._carve_unit_size_bytes("") == 0

    def test_no_instruction_lines_returns_zero(self):
        """Pure directives + labels + blanks contribute no bytes."""
        text = (
            '.section .text, "ax"\n'
            ".align 3\n"
            "glabel foo\n"
            "endlabel foo\n"
        )
        assert cm._carve_unit_size_bytes(text) == 0

    def test_directives_dont_count(self):
        """Only instruction lines (with ``/* HEX HEX HEX */`` comment
        prefix) count.  Directives, labels, blanks, and nonmatching
        markers contribute zero."""
        text = (
            ".section .text, \"ax\"\n"
            ".align 3\n"
            "nonmatching foo, 0x4\n"
            "\n"
            "glabel foo\n"
            "    /* 0 00100000 0800E003 */  jr $ra\n"
            "endlabel foo\n"
        )
        assert cm._carve_unit_size_bytes(text) == 4

    def test_eight_byte_body_with_large_trailing_pad(self):
        """Mirror of ``func_00138BB8``'s shape: 2-insn 8-B body + 8
        trailing nops = 40-B carve unit.  This is the drift case that
        the LCF size fix addresses."""
        text = (
            ".section .text.foo, \"ax\"\n"
            ".align 3\n"
            "nonmatching foo, 0x8\n"
            "\n"
            "glabel foo\n"
            "    /* 0 00100000 0800E003 */  jr $ra\n"
            "    /* 4 00100004 00000000 */   nop\n"
            "endlabel foo\n"
            "    /* 8 00100008 00000000 */  nop\n"
            "    /* C 0010000C 00000000 */  nop\n"
            "    /* 10 00100010 00000000 */  nop\n"
            "    /* 14 00100014 00000000 */  nop\n"
            "    /* 18 00100018 00000000 */  nop\n"
            "    /* 1C 0010001C 00000000 */  nop\n"
            "    /* 20 00100020 00000000 */  nop\n"
            "    /* 24 00100024 00000000 */  nop\n"
        )
        assert cm._carve_unit_size_bytes(text) == 40


# --------------------------------------------------------------------------- #
# _resolve_single_file_targets
# --------------------------------------------------------------------------- #
class TestResolveSingleFileTargets:
    """Five happy paths + three error shapes from the authoritative
    catalog.  Uses synthetic ``CompileUnit`` and ``CarveState`` objects so
    we don't need a real build tree.
    """

    @staticmethod
    def _mkunit(rel: str, kind: str = "asm", root: Path | None = None) -> cm.CompileUnit:
        if root is None:
            root = cm.ROOT
        src = (root / rel).resolve()
        obj = (root / "build" / rel).with_suffix(".o").resolve()
        return cm.CompileUnit(
            src=src, obj=obj, kind=kind, rel=Path(rel)
        )

    @staticmethod
    def _mkcarve(tmp_path: Path, fragment_count: int, carves: dict[str, dict]
                 ) -> cm.CarveState:
        """Build a CarveState with ``fragment_count`` fragments plus one
        carved .s per entry in ``carves``.  ``carves[name]`` is
        ``{tu: Optional[str], size: int}``.
        """
        frag_sources = []
        for i in range(fragment_count):
            fp = tmp_path / f"build/asm/cod/000000.part{i}.s"
            fp.parent.mkdir(parents=True, exist_ok=True)
            fp.write_text(f"; fragment {i}\n")
            frag_sources.append(fp)
        carved_sources = {}
        for name in carves:
            cp = tmp_path / f"build/asm/nonmatching/{name}.s"
            cp.parent.mkdir(parents=True, exist_ok=True)
            cp.write_text(f"; carve {name}\n")
            carved_sources[name] = cp
        entries = [
            cm.CarveEntry(
                name=name,
                unit="asm/cod/000000",
                vaddr=0x100000,
                size=info["size"],
                tu=info.get("tu"),
            )
            for name, info in carves.items()
        ]
        return cm.CarveState(
            original_unit_src=(tmp_path / "asm/cod/000000.s").resolve(),
            original_unit_rel=Path("asm/cod/000000.s"),
            fragment_sources=frag_sources,
            carved_sources=carved_sources,
            entries=entries,
            lcf=tmp_path / "build/SLUS_215.03.lcf",
        )

    # ---- five happy paths ------------------------------------------------ #

    def test_direct_c_tu_match(self, tmp_path, monkeypatch):
        # Point compile.ROOT at the test workspace so the resolver's
        # logging `relative_to(ROOT)` calls don't blow up on tmp paths.
        monkeypatch.setattr(cm, "ROOT", tmp_path)
        (tmp_path / "src/cod").mkdir(parents=True)
        (tmp_path / "src/cod/000000.c").write_text("")
        u = self._mkunit("src/cod/000000.c", kind="c", root=tmp_path)
        log = cm.Logger(verbose=False)
        out = cm._resolve_single_file_targets(
            (tmp_path / "src/cod/000000.c").resolve(),
            carve=None,
            units=[u],
            log=log,
        )
        assert out == [u]

    def test_direct_noncarved_asm_match(self, tmp_path, monkeypatch):
        monkeypatch.setattr(cm, "ROOT", tmp_path)
        (tmp_path / "asm/data/cod").mkdir(parents=True)
        (tmp_path / "asm/data/cod/2BBF80.data.s").write_text("")
        u = self._mkunit("asm/data/cod/2BBF80.data.s", kind="asm", root=tmp_path)
        out = cm._resolve_single_file_targets(
            (tmp_path / "asm/data/cod/2BBF80.data.s").resolve(),
            carve=None,
            units=[u],
            log=cm.Logger(verbose=False),
        )
        assert out == [u]

    def test_direct_build_fragment_match(self, tmp_path, monkeypatch):
        monkeypatch.setattr(cm, "ROOT", tmp_path)
        carve = self._mkcarve(tmp_path, fragment_count=2, carves={})
        u0 = cm.CompileUnit(
            src=carve.fragment_sources[0],
            obj=carve.fragment_sources[0].with_suffix(".o"),
            kind="asm",
            rel=carve.fragment_sources[0].relative_to(tmp_path),
        )
        u1 = cm.CompileUnit(
            src=carve.fragment_sources[1],
            obj=carve.fragment_sources[1].with_suffix(".o"),
            kind="asm",
            rel=carve.fragment_sources[1].relative_to(tmp_path),
        )
        out = cm._resolve_single_file_targets(
            carve.fragment_sources[1].resolve(),
            carve=carve,
            units=[u0, u1],
            log=cm.Logger(verbose=False),
        )
        assert out == [u1]

    def test_carved_monolithic_expands_to_all_fragments(self, tmp_path, monkeypatch):
        monkeypatch.setattr(cm, "ROOT", tmp_path)
        """User names asm/cod/000000.s (the carved-out monolithic) — the
        resolver returns every fragment .o that replaces it.
        """
        # Place a real file at the monolithic source path so .resolve()
        # gives us a stable comparable Path.
        (tmp_path / "asm/cod").mkdir(parents=True)
        (tmp_path / "asm/cod/000000.s").write_text("; monolithic stub\n")
        carve = self._mkcarve(tmp_path, fragment_count=3, carves={})
        # Override the original_unit_src to the file we created.
        carve = cm.CarveState(
            original_unit_src=(tmp_path / "asm/cod/000000.s").resolve(),
            original_unit_rel=Path("asm/cod/000000.s"),
            fragment_sources=carve.fragment_sources,
            carved_sources=carve.carved_sources,
            entries=carve.entries,
            lcf=carve.lcf,
        )
        # Build CompileUnits for the fragments only — the monolithic .s
        # is intentionally NOT in the unit list when a carve is active.
        frag_units = [
            cm.CompileUnit(
                src=fp, obj=fp.with_suffix(".o"), kind="asm",
                rel=fp.relative_to(tmp_path),
            )
            for fp in carve.fragment_sources
        ]
        out = cm._resolve_single_file_targets(
            (tmp_path / "asm/cod/000000.s").resolve(),
            carve=carve,
            units=frag_units,
            log=cm.Logger(verbose=False),
        )
        assert out == frag_units

    def test_tu_owned_carve_remaps_to_owning_c_tu(self, tmp_path, monkeypatch):
        monkeypatch.setattr(cm, "ROOT", tmp_path)
        """User names build/asm/nonmatching/<name>.s for a carve whose
        entry has ``tu``.  The standalone .o doesn't exist (not in unit
        list), so the resolver returns the owning C TU's unit instead.
        """
        carve = self._mkcarve(
            tmp_path, fragment_count=1,
            carves={"func_x": {"size": 4, "tu": "src/cod/000000.c"}},
        )
        # Materialise the C TU file so its .resolve() works.
        (tmp_path / "src/cod").mkdir(parents=True)
        (tmp_path / "src/cod/000000.c").write_text("")
        tu_unit = cm.CompileUnit(
            src=(tmp_path / "src/cod/000000.c").resolve(),
            obj=(tmp_path / "build/src/cod/000000.o").resolve(),
            kind="c",
            rel=Path("src/cod/000000.c"),
        )
        frag_units = [
            cm.CompileUnit(
                src=fp, obj=fp.with_suffix(".o"), kind="asm",
                rel=fp.relative_to(tmp_path),
            )
            for fp in carve.fragment_sources
        ]
        out = cm._resolve_single_file_targets(
            carve.carved_sources["func_x"].resolve(),
            carve=carve,
            units=frag_units + [tu_unit],
            log=cm.Logger(verbose=False),
        )
        assert out == [tu_unit]

    # ---- error shapes ---------------------------------------------------- #

    def test_untracked_path_raises_clear_error(self, tmp_path, monkeypatch):
        monkeypatch.setattr(cm, "ROOT", tmp_path)
        rogue = tmp_path / "src/nope.c"
        rogue.parent.mkdir(parents=True)
        rogue.write_text("")
        with pytest.raises(cm.BuildError, match="not a tracked source"):
            cm._resolve_single_file_targets(
                rogue.resolve(),
                carve=None, units=[],
                log=cm.Logger(verbose=False),
            )

    def test_tu_owned_with_missing_owning_tu_raises(self, tmp_path, monkeypatch):
        monkeypatch.setattr(cm, "ROOT", tmp_path)
        """Resolver expects the TU to be in the unit list when a TU-owned
        carve is named.  If it's missing, raise an internal-invariant
        BuildError instead of silently returning [].
        """
        carve = self._mkcarve(
            tmp_path, fragment_count=1,
            carves={"func_x": {"size": 4, "tu": "src/cod/000000.c"}},
        )
        # No C TU in the unit list — only the fragments.
        frag_units = [
            cm.CompileUnit(
                src=fp, obj=fp.with_suffix(".o"), kind="asm",
                rel=fp.relative_to(tmp_path),
            )
            for fp in carve.fragment_sources
        ]
        with pytest.raises(cm.BuildError, match="not in the discovered unit list"):
            cm._resolve_single_file_targets(
                carve.carved_sources["func_x"].resolve(),
                carve=carve,
                units=frag_units,
                log=cm.Logger(verbose=False),
            )

    def test_monolithic_with_no_fragments_raises(self, tmp_path, monkeypatch):
        monkeypatch.setattr(cm, "ROOT", tmp_path)
        """If a carve is active but its fragments are somehow absent from
        the unit list (e.g. discover() not run), raise rather than return
        []. Guards an internal invariant.
        """
        (tmp_path / "asm/cod").mkdir(parents=True)
        (tmp_path / "asm/cod/000000.s").write_text("")
        carve = self._mkcarve(tmp_path, fragment_count=2, carves={})
        carve = cm.CarveState(
            original_unit_src=(tmp_path / "asm/cod/000000.s").resolve(),
            original_unit_rel=Path("asm/cod/000000.s"),
            fragment_sources=carve.fragment_sources,
            carved_sources=carve.carved_sources,
            entries=carve.entries,
            lcf=carve.lcf,
        )
        with pytest.raises(cm.BuildError, match="no fragments are in the unit list"):
            cm._resolve_single_file_targets(
                (tmp_path / "asm/cod/000000.s").resolve(),
                carve=carve,
                units=[],  # discover() skipped or empty
                log=cm.Logger(verbose=False),
            )


# --------------------------------------------------------------------------- #
# _ld_script_objects
# --------------------------------------------------------------------------- #
class TestLdScriptObjects:

    def test_order_preserving_and_dedup(self, tmp_path):
        lcf = tmp_path / "test.lcf"
        lcf.write_text(textwrap.dedent("""\
            SECTIONS {
                .text : {
                    build/asm/cod/000000.o(.text*)
                    build/asm/data/cod/2BBF80.data.o(.text*)
                    build/asm/cod/000000.o(.data*)
                    build/asm/cod/000000.o(.sbss .scommon)
                    build/asm/data/cod/00460E00.bss.o(.bss COMMON)
                }
            }
        """))
        cfg = _mkcfg(linker_scripts=[str(lcf.relative_to(cm.ROOT))]
                     if lcf.is_relative_to(cm.ROOT) else [])
        # _ld_script_objects resolves relative paths via cm.ROOT, so use
        # an absolute path in the config.  ROOT-relative wouldn't make
        # sense for a tmp_path script anyway.
        cfg = cm.Config(raw={**cfg.raw, "linker_scripts": [str(lcf)]})
        out = cm._ld_script_objects(cfg)
        rels = [p.relative_to(cm.ROOT).as_posix() for p in out]
        assert rels == [
            "build/asm/cod/000000.o",                # first appearance dedups
            "build/asm/data/cod/2BBF80.data.o",
            "build/asm/data/cod/00460E00.bss.o",
        ]

    def test_carve_state_replaces_first_script(self, tmp_path):
        """When a CarveState is passed, ``_ld_script_objects`` parses the
        build-time lcf in place of ``cfg.linker_scripts[0]``.  Models the
        production code path during a carved build.
        """
        # Committed lcf — the one we'd ignore.
        committed = tmp_path / "config/SLUS_215.03.lcf"
        committed.parent.mkdir(parents=True)
        committed.write_text("build/asm/cod/IGNORED.o(.text*)\n")
        # Build-time lcf — the one we should parse.
        build_lcf = tmp_path / "build/SLUS_215.03.lcf"
        build_lcf.parent.mkdir(parents=True)
        build_lcf.write_text(textwrap.dedent("""\
            build/asm/cod/000000.part0.o(.text*)
            build/asm/nonmatching/func_x.o(.text*)
            build/asm/cod/000000.part1.o(.text*)
        """))
        cfg = cm.Config(raw={**_mkcfg().raw,
                             "linker_scripts": [str(committed)]})
        # Stub CarveState — only ``lcf`` is consulted by _ld_script_objects.
        carve = cm.CarveState(
            original_unit_src=Path("/dev/null"),
            original_unit_rel=Path("asm/cod/000000.s"),
            fragment_sources=[],
            carved_sources={},
            entries=[],
            lcf=build_lcf,
        )
        out = cm._ld_script_objects(cfg, carve)
        rels = [p.relative_to(cm.ROOT).as_posix() if p.is_absolute()
                else p.as_posix()
                for p in out]
        assert rels == [
            "build/asm/cod/000000.part0.o",
            "build/asm/nonmatching/func_x.o",
            "build/asm/cod/000000.part1.o",
        ]
        # IGNORED.o from the committed lcf must NOT appear.
        assert not any("IGNORED" in r for r in rels)

    def test_missing_script_is_skipped(self, tmp_path):
        cfg = cm.Config(raw={**_mkcfg().raw,
                             "linker_scripts": [str(tmp_path / "nope.lcf")]})
        assert cm._ld_script_objects(cfg) == []


# --------------------------------------------------------------------------- #
# End-to-end smoke against the real monolithic
# --------------------------------------------------------------------------- #
class TestRealMonolithic:
    """One smoke test that the helpers agree about the *real* asm tree.
    Catches the class of regression where synthetic fixtures pass but
    the function shape in `asm/cod/000000.s` has drifted.
    """

    def test_real_monolithic_indexes_thousands_of_functions(self):
        mono = cm.ROOT / "asm" / "cod" / "000000.s"
        if not mono.exists():
            pytest.skip("asm/cod/000000.s not present (pre-splat checkout)")
        lines = mono.read_text().splitlines(keepends=True)
        idx = cm._index_functions(lines)
        # Live count is ~11,140 glabels in the monolithic text section.
        # Lower bound 1,000 catches regressions while
        # tolerating future re-splat shape drift.
        assert len(idx) > 1000

    def test_real_monolithic_has_func_00100000(self):
        mono = cm.ROOT / "asm" / "cod" / "000000.s"
        if not mono.exists():
            pytest.skip("asm/cod/000000.s not present (pre-splat checkout)")
        lines = mono.read_text().splitlines(keepends=True)
        idx = cm._index_functions(lines)
        assert "func_00100000" in idx
        start, glabel, end = idx["func_00100000"]
        assert lines[start].strip() == ".align 3"
        assert lines[glabel].strip() == "glabel func_00100000"
        assert end > glabel


# --------------------------------------------------------------------------- #
# RelDescriptor + Config.rels parser
# --------------------------------------------------------------------------- #
class TestConfigRels:
    """Lock in the REL schema parser. Pure-Python: no subprocess, no build."""

    _R207_SHA = (
        "ea59932301345e48add7a3eff029b7d0d0138fff1abc67569467880678c653c1"
    )

    @staticmethod
    def _r207_entry() -> dict:
        return {
            "name": "r207",
            "lcf": "config/r207.lcf",
            "sha256_expected": TestConfigRels._R207_SHA,
            "size_expected": 1720,
            "build_path": "build/rel/r207",
            "parts": [
                {"kind": "bin", "path": "bin/rel/r207/header.bin", "size": 60},
                {"kind": "asm", "path": "asm/rel/r207/00003C.s",  "size": 1100},
                {"kind": "bin", "path": "bin/rel/r207/tail.bin",  "size": 560},
            ],
        }

    def test_empty_list_returns_empty(self):
        assert _mkcfg().rels == []

    def test_missing_key_returns_empty(self):
        # No "rels" key at all is treated the same as []; the early
        # baseline never had this field, and configs from that era
        # must keep working without modification.
        cfg = _mkcfg()
        del cfg.raw["asm_sources_glob"]  # unrelated, just to prove
        assert cfg.rels == []

    def test_doc_keys_are_filtered(self):
        cfg = _mkcfg(rels=[
            {"_comment": "doc string"},
            {"name": "_skip_me", "lcf": "x"},   # leading-underscore name
            "not_a_dict",                        # non-dict
            self._r207_entry(),
        ])
        rels = cfg.rels
        assert len(rels) == 1
        assert rels[0].name == "r207"

    def test_full_parse_round_trips_schema(self):
        cfg = _mkcfg(rels=[self._r207_entry()])
        [rel] = cfg.rels
        assert rel.name == "r207"
        assert rel.lcf.name == "r207.lcf"
        assert rel.lcf.is_absolute()
        assert rel.sha256_expected == self._R207_SHA
        assert rel.size_expected == 1720
        assert rel.build_path.name == "r207"
        assert rel.build_path.parent.name == "rel"
        assert [p.kind for p in rel.parts] == ["bin", "asm", "bin"]
        assert sum(p.size for p in rel.parts) == 1720

    def test_sha256_lowercased(self):
        entry = self._r207_entry()
        entry["sha256_expected"] = entry["sha256_expected"].upper()
        cfg = _mkcfg(rels=[entry])
        [rel] = cfg.rels
        assert rel.sha256_expected == self._R207_SHA  # lowercased

    def test_invalid_kind_raises(self):
        entry = self._r207_entry()
        entry["parts"] = [{"kind": "banana", "path": "x", "size": 4}]
        cfg = _mkcfg(rels=[entry])
        with pytest.raises(cm.BuildError, match="invalid part kind"):
            _ = cfg.rels

    def test_empty_parts_raises(self):
        entry = self._r207_entry()
        entry["parts"] = []
        cfg = _mkcfg(rels=[entry])
        with pytest.raises(cm.BuildError, match="parts list is empty"):
            _ = cfg.rels


class TestRelDescriptorPaths:
    """Verify the per-REL path helpers match the lcf's hard-coded
    references (the lcf references ``build/rel/r207/asm/rel/r207/00003C.o``
    by path; if asm_obj_path() drifts, the link silently breaks).
    """

    @staticmethod
    def _r207() -> cm.RelDescriptor:
        return cm.RelDescriptor(
            name="r207",
            lcf=cm.ROOT / "config/r207.lcf",
            sha256_expected="0" * 64,
            size_expected=1720,
            build_path=cm.ROOT / "build/rel/r207",
            parts=[
                cm.RelPart("bin", cm.ROOT / "bin/rel/r207/header.bin", 60),
                cm.RelPart("asm", cm.ROOT / "asm/rel/r207/00003C.s", 1100),
                cm.RelPart("bin", cm.ROOT / "bin/rel/r207/tail.bin", 560),
            ],
        )

    def test_output_rel_path(self):
        r = self._r207()
        assert r.output_rel == cm.ROOT / "build/rel/r207.rel"

    def test_linked_elf_path(self):
        r = self._r207()
        assert r.linked_elf == cm.ROOT / "build/rel/r207/r207.elf"

    def test_text_bin_path(self):
        r = self._r207()
        assert r.text_bin == cm.ROOT / "build/rel/r207/r207.text.bin"

    def test_asm_obj_path_matches_lcf_reference(self):
        r = self._r207()
        [asm_part] = r.asm_parts
        obj = r.asm_obj_path(asm_part)
        # The lcf hard-codes this exact path; if it ever changes,
        # this test fails so the lcf can be updated in lock-step.
        assert (
            obj.relative_to(cm.ROOT).as_posix()
            == "build/rel/r207/asm/rel/r207/00003C.o"
        )

    def test_asm_obj_path_rejects_bin_part(self):
        r = self._r207()
        bin_part = r.bin_parts[0]
        with pytest.raises(cm.BuildError, match="not asm"):
            r.asm_obj_path(bin_part)

    def test_all_objs_orders_by_parts(self):
        r = self._r207()
        assert r.all_objs == [r.asm_obj_path(p) for p in r.asm_parts]

    def test_bin_and_asm_parts_partition_parts(self):
        r = self._r207()
        # parts == bin_parts ∪ asm_parts (order-preserving partition)
        assert len(r.bin_parts) + len(r.asm_parts) == len(r.parts)
        for p in r.bin_parts:
            assert p.kind == "bin"
        for p in r.asm_parts:
            assert p.kind == "asm"


class TestRelDiscoveryExclusion:
    """REL asm parts must be excluded from main-ELF discover().

    Without this guard, ``asm/**/*.s`` globs would sweep REL asm sources
    into the main-ELF unit list and compile them to
    ``build/asm/rel/...`` (instead of the per-REL
    ``build/rel/<name>/asm/rel/...``) on every full build.
    """

    def test_rel_asm_part_paths_empty_when_no_rels(self):
        assert cm._rel_asm_part_paths(_mkcfg()) == set()

    def test_rel_asm_part_paths_collects_asm_only(self, tmp_path):
        # Use real-ish but non-existent paths under ROOT so the set
        # comparison is meaningful (resolve() of a non-existent path
        # works fine on Linux and stays under ROOT).
        asm_p = cm.ROOT / "asm/rel/r207/00003C.s"
        bin_p = cm.ROOT / "bin/rel/r207/header.bin"
        cfg = _mkcfg(rels=[{
            "name": "r207",
            "lcf": "config/r207.lcf",
            "sha256_expected": "0" * 64,
            "size_expected": 1720,
            "build_path": "build/rel/r207",
            "parts": [
                {"kind": "bin", "path": str(bin_p.relative_to(cm.ROOT)),
                 "size": 60},
                {"kind": "asm", "path": str(asm_p.relative_to(cm.ROOT)),
                 "size": 1100},
            ],
        }])
        paths = cm._rel_asm_part_paths(cfg)
        assert paths == {asm_p.resolve()}
        # bin parts are never in the discovery skip set.
        assert bin_p.resolve() not in paths


class TestRelObjdiffUnits:
    """REL units join the auto-emitted main-ELF unit list with a
    ``metadata.rel = <name>`` tag so downstream tooling can tell them
    apart.
    """

    def test_rel_unit_emitted_with_rel_metadata(self):
        cfg = _mkcfg(
            rels=[{
                "name": "r207",
                "lcf": "config/r207.lcf",
                "sha256_expected": "0" * 64,
                "size_expected": 1720,
                "build_path": "build/rel/r207",
                "parts": [
                    {"kind": "bin", "path": "bin/rel/r207/header.bin",
                     "size": 60},
                    {"kind": "asm", "path": "asm/rel/r207/00003C.s",
                     "size": 1100},
                ],
            }],
            objdiff={"target_dir": "expected/build", "base_dir": "build"},
        )
        units = cm._objdiff_units(cfg, carve=None)
        rel_units = [u for u in units if u.get("metadata", {}).get("rel")]
        assert len(rel_units) == 1
        ru = rel_units[0]
        assert ru["metadata"]["rel"] == "r207"
        assert ru["metadata"]["auto_generated"] is True
        assert ru["name"] == "rel/r207/asm/rel/r207/00003C"
        assert ru["base_path"] == "build/rel/r207/asm/rel/r207/00003C.o"
        assert ru["target_path"] == "expected/build/rel/r207/asm/rel/r207/00003C.o"

    def test_no_rel_no_rel_units(self):
        cfg = _mkcfg(
            objdiff={"target_dir": "expected/build", "base_dir": "build"},
        )
        units = cm._objdiff_units(cfg, carve=None)
        assert [u for u in units if u.get("metadata", {}).get("rel")] == []

