#!/usr/bin/env python3
"""Extract the non-loaded ELF sections from SLUS_215.03.

The splat config in `config/SLUS_215.03.yaml` operates on the .rom blob
produced by `objcopy -O binary` — i.e. the contents of the single LOAD
program header (.text + .data + .sndata + .rodata + .gcc_except_table,
plus NOBITS .sbss/.bss).

However, the original ELF contains 43 sections that live *outside* that
LOAD segment and are therefore not in the .rom:

    1× .reginfo            MIPS_REGINFO     0x18 bytes
    1× .DVP.ovlytab        SHT_LOPROC+...   0x1D4 bytes
    1× .DVP.ovlystrtab     STRTAB           0x57C bytes
    1× .mdebug.eabi64      PROGBITS         0    bytes (header only)
   39× .DVP.overlay[N]     SHT_LOPROC+...   various

These are accessed at runtime by the VU0 microcode overlay loader and the
SN Systems debug runtime. To produce a byte-identical ELF we need to be
able to re-emit each as its own section, so we dump them now to
`bin/elf_metadata/` plus a JSON manifest with file offsets, sizes,
addresses, section types, and flags.

Usage:
    python scripts/extract_elf_metadata.py [path/to/SLUS_215.03]

Idempotent.
"""

from __future__ import annotations

import hashlib
import json
import struct
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ELF = REPO_ROOT / "disc_extract" / "SLUS_215.03"
OUT_DIR = REPO_ROOT / "bin" / "elf_metadata"
MANIFEST = OUT_DIR / "manifest.json"

# ELF32 little-endian
EHDR_FMT = "<16sHHIIIIIHHHHHH"
SHDR_FMT = "<IIIIIIIIII"
EHDR_SIZE = struct.calcsize(EHDR_FMT)
SHDR_SIZE = struct.calcsize(SHDR_FMT)


def parse_elf(path: Path):
    raw = path.read_bytes()
    (
        ident,
        e_type,
        e_machine,
        e_version,
        e_entry,
        e_phoff,
        e_shoff,
        e_flags,
        e_ehsize,
        e_phentsize,
        e_phnum,
        e_shentsize,
        e_shnum,
        e_shstrndx,
    ) = struct.unpack(EHDR_FMT, raw[:EHDR_SIZE])

    assert ident[:4] == b"\x7fELF", "not an ELF"
    assert e_shentsize == SHDR_SIZE, f"unexpected shentsize {e_shentsize}"

    # shstrtab
    shstr_off = struct.unpack(SHDR_FMT, raw[e_shoff + e_shstrndx * SHDR_SIZE :][:SHDR_SIZE])[4]
    shstr = raw[shstr_off:]

    sections = []
    for i in range(e_shnum):
        off = e_shoff + i * SHDR_SIZE
        (
            sh_name,
            sh_type,
            sh_flags,
            sh_addr,
            sh_offset,
            sh_size,
            sh_link,
            sh_info,
            sh_addralign,
            sh_entsize,
        ) = struct.unpack(SHDR_FMT, raw[off : off + SHDR_SIZE])
        name_end = shstr.index(b"\x00", sh_name)
        name = shstr[sh_name:name_end].decode("ascii", "replace")
        sections.append(
            dict(
                idx=i,
                name=name,
                sh_type=sh_type,
                sh_flags=sh_flags,
                sh_addr=sh_addr,
                sh_offset=sh_offset,
                sh_size=sh_size,
                sh_link=sh_link,
                sh_info=sh_info,
                sh_addralign=sh_addralign,
                sh_entsize=sh_entsize,
            )
        )

    return raw, e_flags, sections, e_shoff, e_shnum, e_shstrndx


# Section names whose payload is part of the LOAD segment and therefore
# already included in the .rom blob. We skip these here.
LOAD_SEGMENT_SECTIONS = {
    ".text",
    ".data",
    ".sndata",
    ".rodata",
    ".gcc_except_table",
    ".sbss",
    ".bss",
}

# Pure-metadata / no-payload sections that we also skip (they don't need
# to be re-emitted byte-for-byte from a bin file).
SKIP_SECTIONS = {
    "",  # null section [0]
    ".shstrtab",  # section name string table — regenerated by linker
}


def safe_filename(name: str, idx: int) -> str:
    """ELF sections can repeat names (`.DVP.overlay[...]` ×39).
    Stash by section index to keep them unique on disk."""
    base = name.lstrip(".").replace(".", "_").replace("[", "_").replace("]", "_") or "noname"
    return f"sec{idx:02d}_{base}.bin"


def main():
    elf_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_ELF
    raw, e_flags, sections, e_shoff, e_shnum, e_shstrndx = parse_elf(elf_path)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    manifest = {
        "source_elf": str(elf_path.relative_to(REPO_ROOT)) if elf_path.is_relative_to(REPO_ROOT) else str(elf_path),
        "source_sha256": hashlib.sha256(raw).hexdigest(),
        "e_flags": f"0x{e_flags:08x}",
        "sections": [],
    }

    # The .shstrtab is pure metadata (only contains C-string section names
    # plus historical .symtab/.strtab leading entries that survive strip).
    # Dumping it lets the post-link ELF synthesiser splice the retail
    # byte-identical section header string table back in without having to
    # carry the leading-string archaeology in code.
    shstr_ent = struct.unpack(
        SHDR_FMT, raw[e_shoff + e_shstrndx * SHDR_SIZE :][:SHDR_SIZE]
    )
    shstr_bytes = raw[shstr_ent[4] : shstr_ent[4] + shstr_ent[5]]
    (OUT_DIR / "shstrtab.bin").write_bytes(shstr_bytes)
    manifest["shstrtab"] = {
        "sh_offset":      shstr_ent[4],
        "sh_offset_hex":  f"0x{shstr_ent[4]:x}",
        "sh_size":        shstr_ent[5],
        "sh_size_hex":    f"0x{shstr_ent[5]:x}",
        "payload":        "bin/elf_metadata/shstrtab.bin",
        "payload_sha256": hashlib.sha256(shstr_bytes).hexdigest(),
    }

    # The section header table also lives outside the LOAD segment and is
    # purely metadata.  Record its location and bytes for the synthesiser.
    sht_bytes = raw[e_shoff : e_shoff + e_shnum * SHDR_SIZE]
    (OUT_DIR / "sht.bin").write_bytes(sht_bytes)
    manifest["sht"] = {
        "e_shoff":        e_shoff,
        "e_shoff_hex":    f"0x{e_shoff:x}",
        "e_shnum":        e_shnum,
        "e_shstrndx":     e_shstrndx,
        "shentsize":      SHDR_SIZE,
        "payload":        "bin/elf_metadata/sht.bin",
        "payload_sha256": hashlib.sha256(sht_bytes).hexdigest(),
    }

    # Total retail ELF size — useful for the synthesiser to right-size the
    # output and for sanity checks.
    manifest["total_size"] = len(raw)
    manifest["total_size_hex"] = f"0x{len(raw):x}"

    extracted = 0
    skipped_loaded = 0
    for s in sections:
        name = s["name"]
        if name in SKIP_SECTIONS:
            continue
        if name in LOAD_SEGMENT_SECTIONS:
            skipped_loaded += 1
            continue
        entry = dict(s)
        entry["sh_type_hex"] = f"0x{s['sh_type']:08x}"
        entry["sh_flags_hex"] = f"0x{s['sh_flags']:08x}"
        entry["sh_addr_hex"] = f"0x{s['sh_addr']:08x}"
        entry["sh_offset_hex"] = f"0x{s['sh_offset']:x}"
        entry["sh_size_hex"] = f"0x{s['sh_size']:x}"

        if s["sh_type"] == 8:  # SHT_NOBITS
            entry["payload"] = None
        elif s["sh_size"] == 0:
            entry["payload"] = None  # e.g. .mdebug.eabi64 (header only)
        else:
            payload = raw[s["sh_offset"] : s["sh_offset"] + s["sh_size"]]
            fname = safe_filename(name, s["idx"])
            (OUT_DIR / fname).write_bytes(payload)
            entry["payload"] = f"bin/elf_metadata/{fname}"
            entry["payload_sha256"] = hashlib.sha256(payload).hexdigest()
            extracted += 1

        manifest["sections"].append(entry)

    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")
    print(
        f"Extracted {extracted} payload section(s) → {OUT_DIR.relative_to(REPO_ROOT)}/, "
        f"skipped {skipped_loaded} loaded section(s) already in .rom. "
        f"Manifest: {MANIFEST.relative_to(REPO_ROOT)}"
    )


if __name__ == "__main__":
    main()
