#!/usr/bin/env python3
"""report_lint.py — internal-consistency gate for progress/report.json.

``progress/report.json`` is generated by ``objdiff-cli`` (which needs the
vendored toolchain and the disc-derived target objects), so it CANNOT be
regenerated in a toolchain-free CI runner.  The committed report is what
decomp.dev ingests and what the badges render, which means a hand-edited
report — one that inflates ``matched_code`` / ``matched_functions`` or a
``*_percent`` without touching the underlying detail — would otherwise go
unnoticed.

This lint re-derives the headline ``measures`` from the per-unit and
per-function detail in the same file and fails on any disagreement.  It
proves the report is *self-consistent*; it does NOT (and cannot, without
the toolchain) prove the report matches a real build.

Checks:
  - ``measures`` and ``units`` are present and well-typed.
  - byte/count fields are integers; ``matched_* <= total_*``.
  - every ``*_percent`` is in ``[0, 100]`` and agrees (within rounding)
    with its underlying byte/count integers.
  - ``total_units == len(units)``.
  - ``total_functions`` / ``matched_functions`` equal the count / the
    100%-matched count re-derived from the per-function detail.

Usage:
    python3 scripts/checks/report_lint.py            # lint progress/report.json
    python3 scripts/checks/report_lint.py PATH       # lint a specific file

Exit codes: 0 = consistent, 1 = inconsistency found, 77 = skip (no report).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_REPORT = ROOT / "progress" / "report.json"

# Absolute tolerance (percentage points) when re-deriving a *_percent field
# from its integer byte/count source.  objdiff writes rounded percents; the
# lint must never trip on rounding.
PCT_TOL = 0.05

# Headline integer fields objdiff stores as strings (bytes) or numbers (counts).
_INT_FIELDS = (
    "matched_code", "total_code",
    "matched_data", "total_data",
    "matched_functions", "total_functions",
    "total_units",
)
_PCT_FIELDS = (
    "fuzzy_match_percent", "matched_code_percent",
    "matched_data_percent", "matched_functions_percent",
)


def _to_int(value):
    """Coerce objdiff's string-or-number byte/count field to int, or None."""
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _pct(num, den):
    return 0.0 if den == 0 else 100.0 * num / den


def _in_range(value):
    return isinstance(value, (int, float)) and 0.0 <= value <= 100.0


def lint_report(report) -> list[str]:
    """Return a list of consistency problems (empty list == clean)."""
    if not isinstance(report, dict):
        return ["report is not a JSON object"]

    measures = report.get("measures")
    if not isinstance(measures, dict):
        return ["report has no 'measures' object"]

    problems: list[str] = []

    units = report.get("units")
    if not isinstance(units, list):
        problems.append("report has no 'units' array")
        units = []

    # Integer fields parse.
    ints: dict[str, int] = {}
    for key in _INT_FIELDS:
        if key in measures:
            parsed = _to_int(measures[key])
            if parsed is None:
                problems.append(f"measures.{key} is not an integer: {measures[key]!r}")
            else:
                ints[key] = parsed

    # matched_* <= total_*.
    for matched, total in (
        ("matched_code", "total_code"),
        ("matched_data", "total_data"),
        ("matched_functions", "total_functions"),
    ):
        if matched in ints and total in ints and ints[matched] > ints[total]:
            problems.append(
                f"measures.{matched} ({ints[matched]}) exceeds "
                f"{total} ({ints[total]})"
            )

    # Percents in [0, 100].
    for key in _PCT_FIELDS:
        if key in measures and not _in_range(measures[key]):
            problems.append(f"measures.{key} out of range [0,100]: {measures[key]!r}")

    # Percent agrees with its integer source.
    for pct_key, num_key, den_key in (
        ("matched_code_percent", "matched_code", "total_code"),
        ("matched_data_percent", "matched_data", "total_data"),
        ("matched_functions_percent", "matched_functions", "total_functions"),
    ):
        value = measures.get(pct_key)
        if isinstance(value, (int, float)) and num_key in ints and den_key in ints:
            want = _pct(ints[num_key], ints[den_key])
            if abs(value - want) > PCT_TOL:
                problems.append(
                    f"measures.{pct_key} ({value}) disagrees with "
                    f"{num_key}/{den_key} ({want:.4f})"
                )

    # total_units == len(units).
    if "total_units" in ints and ints["total_units"] != len(units):
        problems.append(
            f"measures.total_units ({ints['total_units']}) != "
            f"len(units) ({len(units)})"
        )

    # Re-derive function totals from the per-function detail.
    detail_total = 0
    detail_matched = 0
    for unit in units:
        if not isinstance(unit, dict):
            problems.append("units contains a non-object entry")
            continue
        uname = unit.get("name", "<unnamed>")
        um = unit.get("measures")
        if isinstance(um, dict) and um.get("fuzzy_match_percent") is not None:
            if not _in_range(um["fuzzy_match_percent"]):
                problems.append(
                    f"unit {uname}: fuzzy_match_percent out of range: "
                    f"{um['fuzzy_match_percent']!r}"
                )
        for fn in unit.get("functions") or []:
            detail_total += 1
            fname = fn.get("name", "<unnamed>")
            if "size" in fn and _to_int(fn["size"]) is None:
                problems.append(
                    f"unit {uname}: function {fname} size not an integer: "
                    f"{fn['size']!r}"
                )
            # objdiff records an unmatched function with a null percent;
            # that counts toward the total but is not a match and is not
            # an error.
            fv = fn.get("fuzzy_match_percent")
            if fv is None:
                continue
            if not _in_range(fv):
                problems.append(
                    f"unit {uname}: function {fname} "
                    f"fuzzy_match_percent out of range: {fv!r}"
                )
                continue
            if fv == 100.0:
                detail_matched += 1

    if "total_functions" in ints and ints["total_functions"] != detail_total:
        problems.append(
            f"measures.total_functions ({ints['total_functions']}) != "
            f"functions in detail ({detail_total})"
        )
    if "matched_functions" in ints and ints["matched_functions"] != detail_matched:
        problems.append(
            f"measures.matched_functions ({ints['matched_functions']}) != "
            f"100%-matched functions in detail ({detail_matched})"
        )

    # complete_code ("fully linked") — optional axis. When present, re-derive
    # it from the per-unit ``metadata.complete`` flags exactly as objdiff-cli /
    # scripts/mark_complete.py do (sum of complete units' total_code), so a
    # hand-patched *or* a legitimately regenerated report both pass.
    if "complete_code" in measures:
        cc = _to_int(measures["complete_code"])
        if cc is None:
            problems.append(
                f"measures.complete_code is not an integer: "
                f"{measures['complete_code']!r}"
            )
        else:
            if "total_code" in ints and cc > ints["total_code"]:
                problems.append(
                    f"measures.complete_code ({cc}) exceeds "
                    f"total_code ({ints['total_code']})"
                )
            derived = 0
            for unit in units:
                if not isinstance(unit, dict):
                    continue
                if (unit.get("metadata") or {}).get("complete"):
                    derived += _to_int((unit.get("measures") or {}).get("total_code")) or 0
            if cc != derived:
                problems.append(
                    f"measures.complete_code ({cc}) != sum of complete "
                    f"units' total_code ({derived})"
                )
        ccp = measures.get("complete_code_percent")
        if ccp is not None:
            if not _in_range(ccp):
                problems.append(
                    f"measures.complete_code_percent out of range [0,100]: {ccp!r}"
                )
            elif cc is not None and "total_code" in ints:
                want = _pct(cc, ints["total_code"])
                if abs(ccp - want) > PCT_TOL:
                    problems.append(
                        f"measures.complete_code_percent ({ccp}) disagrees with "
                        f"complete_code/total_code ({want:.4f})"
                    )

    return problems


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Lint progress/report.json for internal consistency."
    )
    parser.add_argument(
        "report",
        nargs="?",
        default=str(DEFAULT_REPORT),
        help="path to report.json (default: progress/report.json)",
    )
    args = parser.parse_args(argv)

    path = Path(args.report)
    if not path.is_file():
        print(f"report_lint: {path} missing — nothing to check (skip).")
        return 77
    try:
        report = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError) as exc:
        print(f"report_lint: cannot parse {path}: {exc}")
        return 1

    problems = lint_report(report)
    if problems:
        print(f"report_lint: {len(problems)} consistency problem(s) in {path}:")
        for problem in problems:
            print(f"   - {problem}")
        return 1
    print(f"report_lint: {path} is internally consistent.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
